version: '3'


services:
  final-micro:
    build: ../final-2025-02-04-lab-iv-v2-405063-zarza-mateo
    image: final-app
    ports:
      - "8080:8080"
    environment:
      APP_NAME: final-app
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/final_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - final-network


  mysql:
    image: mysql:8
    container_name: final-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - final-network
    restart: always

volumes:
  mysql-data:


networks:
  final-network:
    driver: bridge
